define([], function() {
    return {
        COLOR_CONVERSION_THRESHOLD: 45,

        APPEARANCE_THRESHOLD: 45,
        DEFAULT_PIXEL_COLOR_THRESHOLD: 20,
        STRICT_PIXEL_COLOR_THRESHOLD: 45,
        INVISIBLE_COLOR_PERCENTAGE: 42,

        OVERLAPPING_LAYER_PERCENTAGE: 20,

        INITIAL_FONT_SIZE_SCALE_FACTOR: 0.07
    };
});